
apiVersion: v1
kind: Namespace
metadata:
  name: 07-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: podinfo-pvc
  namespace: 07-pvc
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: podinfo-deployment
  namespace: 07-pvc
  labels:
    app: podinfo
spec:
  selector:
    matchLabels:
      app: podinfo
  template:
    metadata:
      labels:
        app: podinfo
    spec:
      containers:
        - name: podinfo
          image: stefanprodan/podinfo:latest
          volumeMounts:
            - name: pvc-volume
              mountPath: /data
      volumes:
        - name: pvc-volume
          persistentVolumeClaim:
            claimName: podinfo-pvc
