
apiVersion: v1
kind: Namespace
metadata:
  name: 06-secret
---
apiVersion: v1
kind: Secret
metadata:
  name: podinfo-secret
  namespace: 06-secret
stringData:
  STRING_SECRET: "Hello from Secret!"
data:
  BASE64_SECRET: SGVsbG8gZnJvbSBTZWNyZXQh
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: podinfo-deployment
  namespace: 06-secret
  labels:
    app: podinfo
spec:
  selector:
    matchLabels:
      app: podinfo
  template:
    metadata:
      labels:
        app: podinfo
    spec:
      containers:
        - name: podinfo
          image: stefanprodan/podinfo:latest
          envFrom:
            - secretRef:
                name: podinfo-secret
