
apiVersion: v1
kind: Namespace
metadata:
  name: 04-replica-set
---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: podinfo-replica-set
  namespace: 04-replica-set
  labels:
    app: podinfo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: podinfo
  template:
    metadata:
      labels:
        app: podinfo
    spec:
      containers:
        - name: podinfo
          image: stefanprodan/podinfo:latest
